# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
        terraform {
            required_providers{
                aws = {
                    source = "hashicorp/aws"
                    version = "~> 3.27"
                }
            }
        }

        provider "aws" {
            region = "ap-south-1"
            profile = "terra-admin"
        }
